### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jbull477/tc-359-project3#1]
:+1: Looks good - it only hurt my eyeballs a little. :smiley: I don't have any new comments I haven't mentioned in a previous project, except that I think it looks a little cleaner to have a space before the opening brace in CSS. For example, I'd change:

``` css
body{ 
  background-image: url("../images/face.png");
} 
```

to:

``` css
body { 
  background-image: url("../images/face.png");
} 
```
